export const products = [
    {
        nombre:"Remera React",
        imagen:"./img/Inicio/react.jpg",
        precio:"$120.000",
        id:"1",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Js",
        imagen:"./img/Inicio/js.jpg",
        precio:"$120.000",
        id:"2",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera HTML",
        imagen:"./img/Inicio/html.jpg",
        precio:"$120.000",
        id:"3",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Git",
        imagen:"./img/Inicio/git.jpg",
        precio:"$120.000",
        id:"4",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera TS",
        imagen:"./img/Inicio/ts.jpg",
        precio:"$120.000",
        id:"5",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Vue",
        imagen:"./img/Inicio/vue.jpg",
        precio:"$120.000",
        id:"6",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Node",
        imagen:"./img/Inicio/node.jpg",
        precio:"$120.000",
        id:"7",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Sass",
        imagen:"./img/Inicio/sass.jpg",
        precio:"$120.000",
        id:"8",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Drupal",
        imagen:"./img/Inicio/drupal.jpg",
        precio:"$120.000",
        id:"9",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Sonic",
        imagen:"../img/Kids/sonic.jpg",
        precio:"$65.000",
        id:"10",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Goku",
        imagen:"../img/Kids/goku.jpg",
        precio:"$65.000",
        id:"11",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Spiderman",
        imagen:"'../img/Kids/spiderman.jpg",
        precio:"$65.000",
        id:"12",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Ajedrez",
        imagen:"../img/Kids/ajedrez.jpg",
        precio:"$65.000",
        id:"13",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Astronauta",
        imagen:"../img/Kids/astronauta.jpg",
        precio:"$65.000",
        id:"14",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Classic",
        imagen:"../img/Kids/classic.jpg",
        precio:"$65.000",
        id:"15",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Cube",
        imagen:"../img/Kids/cube.jpg",
        precio:"$65.000",
        id:"16",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Stark",
        imagen:"../img/Kids/stark.jpg",
        precio:"$65.000",
        id:"17",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Rock",
        imagen:"../img/Kids/rock.png",
        precio:"$65.000",
        id:"18",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Remera Jordan",
        imagen:"./img/Adultos/images.jpg",
        precio:"$85.000",
        id:"19",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Pico",
        imagen:"../img/Adultos/pico.jpg",
        precio:"$85.000",
        id:"20",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Adidas",
        imagen:"../img/Adultos/addidas.jpg",
        precio:"$85.000",
        id:"21",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Mountain",
        imagen:"../img/Adultos/mountain.jpg",
        precio:"$85.000",
        id:"22",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Nordic",
        imagen:"../img/Adultos/nordic.jpg",
        precio:"$85.000",
        id:"23",
        stock: "6",
        description:"",
        category: "",
    },       
    {
        nombre:"Remera Fish",
        imagen:"../img/Adultos/fish.jpg",
        precio:"$85.000",
        id:"24",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Auto",
        imagen:"../img/Adultos/auto.jpg",
        precio:"$85.000",
        id:"25",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Versace",
        imagen:"../img/Adultos/versace.jpg",
        precio:"$85.000",
        id:"26",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Remera Puma",
        imagen:"../img/Adultos/puma.jpg",
        precio:"$85.000",
        id:"27",
        stock: "6",
        description:"",
        category: "",
    },
    {
        nombre:"Giftcard Classic",
        imagen:"../img/Gift Card/15-.png",
        precio:"$35.000",
        id:"28",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Giftcard Premium",
        imagen:"../img/Gift Card/25-.png",
        precio:"$45.000",
        id:"29",
        stock: "6",
        description:"",
        category: "",
    },        
    {
        nombre:"Giftcard Exclusive",
        imagen:"../img/Gift Card/50-.png",
        precio:"$80.000",
        id:"30",
        stock: "6",
        description:"",
        category: "",
    }
]