export const products = [
    {
        title:"Remera React",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658186/react_mtgtqr.jpg",
        price:"$120.000",
        id:"1",
        stock: "10",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Js",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658185/js_oymlq8.jpg",
        price:"$120.000",
        id:"2",
        stock: "8",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera HTML",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658183/html_jqk41m.jpg",
        price:"$120.000",
        id:"3",
        stock: "9",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Git",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658184/git_r3terj.jpg",
        price:"$120.000",
        id:"4",
        stock: "7",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera TS",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658185/ts_cypaja.jpg",
        price:"$120.000",
        id:"5",
        stock: "6",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Vue",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658186/vue_d8u9bc.jpg",
        price:"$120.000",
        id:"6",
        stock: "6",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Node",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658183/node_cqddze.jpg",
        price:"$120.000",
        id:"7",
        stock: "6",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Sass",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658188/sass_ucum5o.jpg",
        price:"$120.000",
        id:"8",
        stock: "6",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Drupal",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658183/drupal_q6chm7.jpg",
        price:"$120.000",
        id:"9",
        stock: "6",
        description:"",
        category: "Inicio",
    },
    {
        title:"Remera Sonic",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658188/sonic_dtwhlg.jpg",
        price:"$65.000",
        id:"10",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Goku",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658188/goku_lmgt3s.jpg",
        price:"$65.000",
        id:"11",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Spiderman",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658188/spiderman_tq7xah.jpg",
        price:"$65.000",
        id:"12",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Ajedrez",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658186/ajedrez_xnjj37.jpg",
        price:"$65.000",
        id:"13",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Astronauta",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658186/astronauta_evc3bz.jpg",
        price:"$65.000",
        id:"14",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Classic",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658187/classic_rw21no.jpg",
        price:"$65.000",
        id:"15",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Cube",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658188/cube_esgblu.jpg",
        price:"$65.000",
        id:"16",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Stark",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658189/stark_jgshwr.jpg",
        price:"$65.000",
        id:"17",
        stock: "6",
        description:"",
        category: "Kids",
    },        
    {
        title:"Remera Rock",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658189/rock_fhdmmt.png",
        price:"$65.000",
        id:"18",
        stock: "6",
        description:"",
        category: "Kids",
    },
    {
        title:"Remera Jordan",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658190/images_yosltm.jpg",
        price:"$85.000",
        id:"19",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Pico",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658191/pico_kttcsp.jpg",
        price:"$85.000",
        id:"20",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Adidas",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658190/addidas_z6jwbr.jpg",
        price:"$85.000",
        id:"21",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Mountain",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658190/mountain_uejzcg.jpg",
        price:"$85.000",
        id:"22",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Nordic",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658190/nordic_bnsonj.jpg",
        price:"$85.000",
        id:"23",
        stock: "6",
        description:"",
        category: "Adultos",
    },       
    {
        title:"Remera Fish",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658190/fish_efayia.jpg",
        price:"$85.000",
        id:"24",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Auto",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658192/auto_ogxuet.jpg",
        price:"$85.000",
        id:"25",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Versace",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658192/versace_irchsz.jpg",
        price:"$85.000",
        id:"26",
        stock: "6",
        description:"",
        category: "Adultos",
    },        
    {
        title:"Remera Puma",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658191/puma_m6drru.jpg",
        price:"$85.000",
        id:"27",
        stock: "6",
        description:"",
        category: "Adultos",
    },
    {
        title:"Giftcard Classic",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658192/15-_sb4hsg.png",
        price:"$35.000",
        id:"28",
        stock: "6",
        description:"",
        category: "Giftcard",
    },        
    {
        title:"Giftcard Premium",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658192/25-_bt9mt6.png",
        price:"$45.000",
        id:"29",
        stock: "6",
        description:"",
        category: "Giftcard",
    },        
    {
        title:"Giftcard Exclusive",
        imageUrl:"https://res.cloudinary.com/dwf9gj6mq/image/upload/v1728658193/50-_nuntzf.png",
        price:"$80.000",
        id:"30",
        stock: "6",
        description:"",
        category: "Giftcard",
    }
]